spring:
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/account
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: validate
    show-sql: true
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8090/realms/master
        registration:
          keycloak:
            authorizationGrantType: client_credentials
            provider: keycloak
            client-id: account-service
            client-secret: ${CLIENT_SECRET:DYs0kSOoYyxMQVFg3yiprnueJ87C5AwL}
            redirect-uri: '{baseUrl}/{action}/oauth2/code/{registrationId}'
            scope: openid, profile, email
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8090/realms/master
server:
  port: 8020