spring:
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring:
          json:
            type:
              mapping: cashActionResult:ru.azmeev.bank.cash.web.dto.CashActionResult
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: ${ISSUER_URI:http://localhost:8090/realms/master}
        registration:
          keycloak:
            authorizationGrantType: client_credentials
            provider: keycloak
            client-id: cash-service
            client-secret: ${CLIENT_SECRET:I0StlCY5tNJTvaIbPJdiMBgGtmIR5yN1}
            redirect-uri: '{baseUrl}/{action}/oauth2/code/{registrationId}'
            scope: openid, profile, email
      resourceserver:
        jwt:
          issuer-uri: ${ISSUER_URI:http://localhost:8090/realms/master}

server:
  port: 8030

service:
  account:
    url: lb://gateway-service/account
  blocker:
    url: lb://gateway-service/blocker

kafka:
  topics:
    cash-notification: cash.notification.msg

management:
  zipkin:
    tracing:
      endpoint:  http://127.0.0.1:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1