spring:
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      acks: 0
      retries: 0
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      max-in-flight-requests: 1
      properties:
        spring:
          json:
            type:
              mapping: exchangeRateList:ru.azmeev.bank.exchangegenerator.dto.ExchangeRateList
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: ${ISSUER_URI:http://localhost:8090/realms/master}
        registration:
          keycloak:
            authorizationGrantType: client_credentials
            provider: keycloak
            client-id: exchange-generator-service
            client-secret: ${CLIENT_SECRET:WWjquJ7Uz2owLuo0v6Ptibn2jZ288B80}
            redirect-uri: '{baseUrl}/{action}/oauth2/code/{registrationId}'
            scope: openid, profile, email
      resourceserver:
        jwt:
          issuer-uri: ${ISSUER_URI:http://localhost:8090/realms/master}
server:
  port: 8061

kafka:
  topics:
    exchange-topic: exchange-messages
