spring:
  application:
    name: cash-service
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8090/realms/master
        registration:
          keycloak:
            authorizationGrantType: client_credentials
            provider: keycloak
            client-id: cash-service
            client-secret: ${CLIENT_SECRET:I0StlCY5tNJTvaIbPJdiMBgGtmIR5yN1}
            redirect-uri: '{baseUrl}/{action}/oauth2/code/{registrationId}'
            scope: openid, profile, email
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8090/realms/master

server:
  port: 8030

service:
  account:
    url: http://localhost:8020
  blocker:
    url: http://localhost:8070
  notifications:
    url: http://localhost:8080