apiVersion: v2
name: zipkin
description: Zipkin chart
version: 1.0.0
appVersion: "1.3.6"
dependencies:
  - name: zipkin
    version: "1.3.6"
    repository: "oci://registry-1.docker.io/bitnamicharts"
    condition: zipkin.enabled