replicaCount: 1

image:
  repository: notification-service
  pullPolicy: IfNotPresent
  tag: "0.0.1-SNAPSHOT"

service:
  type: ClusterIP
  port: 80

kafka:
  consumer:
    groupId: "notification-service"
    autoOffsetReset: "latest"
    trustedPackages: "ru.azmeev.bank.*"
    typeMappings: "cashActionResult:ru.azmeev.bank.notification.dto.CashActionResult,transferActionResult:ru.azmeev.bank.notification.dto.TransferActionResult"