spring:
  application:
    name: front-service
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/front
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: validate
    show-sql: true

server:
  port: 8010