services:
  jenkins:
    build: .
    container_name: jenkins
    user: root
    privileged: true
    env_file:
      - .env
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
      - DOCKER_HOST=unix:///var/run/docker.sock
      - TESTCONTAINERS_HOST_OVERRIDE=host.docker.internal
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ${KUBECONFIG_PATH}:/root/.kube/config
      - ${MINIKUBE_PATH}:/root/.minikube

volumes:
  jenkins_home: